# Generated by Django 3.2.8 on 2021-11-10 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cuisine',
            new_name='cuisines',
        ),
    ]
