# Generated by Django 3.2.8 on 2021-11-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='into',
            new_name='info',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(choices=[('none', 'None'), ('mexican', 'Mexican'), ('breakfast', 'Breakfast')], default='none', max_length=20),
        ),
    ]
