# Generated by Django 3.2.8 on 2021-11-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instruction',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='measurement',
            field=models.CharField(blank=True, choices=[('Oz', 'Oz'), ('Cup', 'Cup'), ('Tsp', 'Tsp'), ('Tbsp', 'Tbsp')], default='None', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Instruction',
        ),
    ]
