# Generated by Django 3.2.8 on 2021-11-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_cuisine_recipe_cuisines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cuisines',
            field=models.CharField(blank=True, choices=[], default='None', max_length=20, null=True),
        ),
    ]
