# Generated by Django 3.2.8 on 2021-11-18 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20211118_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.OneToOneField(default='None', on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient'),
        ),
    ]
