# Generated by Django 3.2.8 on 2021-11-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_cuisines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cuisines',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(blank=True, choices=[('Mexican', 'Mexican'), ('Asian', 'Asian'), ('American', 'American'), ('Indian', 'Indian')], default='None', max_length=20, null=True),
        ),
    ]
