# Generated by Django 3.2.8 on 2022-01-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20220129_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='body',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(default=2, max_length=240),
            preserve_default=False,
        ),
    ]
