# Generated by Django 3.2.8 on 2021-11-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20211111_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='info',
            field=models.CharField(max_length=500),
        ),
    ]
